name: publish-for-blender-snapshot

on:
  schedule:
    - cron: "0 0 * * *" # Run at 00:00 UTC
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:
    name: Build Blender
    runs-on: ubuntu-latest

    steps:
    - name: Install Tools
      run: | 
        sudo apt update && \
        sudo apt install -y build-essential cmake libembree-dev \
          libxi-dev libxxf86vm-dev libboost-dev libboost-locale-dev libgl1-mesa-dev \
          libavformat-dev libtbb-dev libswscale-dev libavdevice-dev libblas3 \
          libzstd-dev

    - name: Install Python
      uses: actions/setup-python@v2.3.1
      with: 
        python-version: "${{env.PYTHON_VERSION}}"

    - name: Install Python Dependencies
      run: | 
        curl https://bootstrap.pypa.io/get-pip.py | python && \
        python -m pip install numpy requests cython

    - name: Setup Python Path
      run: |
        sudo sh -c "echo '$pythonLocation/lib' >> /etc/ld.so.conf.d/python.conf" && \
        sudo ldconfig

    - name: Checkout Blender
      run: git clone --depth=1 git://git.blender.org/blender.git

    - name: Checkout addons
      run: git clone --depth=1 git://git.blender.org/blender-addons.git

    - name: Checkout addons-contrib
      run: git clone --depth=1 git://git.blender.org/blender-addons-contrib.git

    - name: Checkout translations
      run: git clone --depth=1 git://git.blender.org/blender-translations.git

    - name: Checkout dev-tools
      run: git clone --depth=1 git://git.blender.org/blender-dev-tools.git

    - name: Update Submodules
      run: git -C blender submodule update --init --recursive --remote

    - name: Configure CMake
      run: |
        cmake -S blender -B build \
                 -C blender/build_files/cmake/config/blender_release.cmake \
                 -DCMAKE_BUILD_TYPE=Release \
                 -DWITH_INSTALL_PORTABLE=ON \
                 -DWITH_MOD_OCEANSIM=OFF \
                 -DWITH_CYCLES=OFF \
                 -DPYTHON_VERSION=${{env.PYTHON_VERSION}}

    - name: Build Blender
      run:  make -C build -j `nproc`

    - name: Copy Release Scripts
      run: make -C build install

    - name: Archive Build
      if: ${{ !env.ACT }}
      run: tar zcvf build.tar.gz build

    - name: Upload Build
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: blender
        path: build.tar.gz
        retention-days: 3

  build_api:
    name: Build API Documentation
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Download Build
      if: ${{ !env.ACT }}
      uses: actions/download-artifact@v2
      with:
        name: blender

    - name: Extract Build
      if: ${{ !env.ACT }}
      run: tar zxvf build.tar.gz

    - name: Install Tools
      run: | 
        sudo apt update && \
        sudo apt install -y libtbb2 libxi6 libxxf86vm1 libxfixes3 libgl1 \
          libavformat58 libavdevice58 libboost-locale1.71.0

    - name: Install Python
      uses: actions/setup-python@v2.3.1
      with: 
        python-version: "${{env.PYTHON_VERSION}}"

    - name: Install Python Dependencies
      run: | 
        curl https://bootstrap.pypa.io/get-pip.py | python && \
        python -m pip install sphinx yapf tqdm numpy

    - name: Setup Python Path
      run: |
        sudo sh -c "echo '$pythonLocation/lib' >> /etc/ld.so.conf.d/python.conf" && \
        sudo ldconfig

    - name: Checkout Blender
      run: git clone --depth=1 git://git.blender.org/blender.git

    - name: Prepare API Documentation
      working-directory: build
      run: | 
        bin/blender --background -noaudio --factory-startup \
                    --python ../blender/doc/python_api/sphinx_doc_gen.py -- \
                    --output "${{ github.workspace }}/python_api"

    - name: Archive Documents
      if: ${{ !env.ACT }}
      run: tar zcvf apidocs.tar.gz python_api

    - name: Upload Documents
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: apidocs
        path: apidocs.tar.gz
        retention-days: 3

  publish_stubs:
    name: Publish API Stubs
    runs-on: ubuntu-latest
    needs: [build_api]

    steps:
    - name: Download Build
      if: ${{ !env.ACT }}
      uses: actions/download-artifact@v2
      with:
        name: blender

    - name: Extract Build
      if: ${{ !env.ACT }}
      run: tar zxvf build.tar.gz

    - name: Download Documents
      if: ${{ !env.ACT }}
      uses: actions/download-artifact@v2
      with:
        name: apidocs

    - name: Extract Documents
      if: ${{ !env.ACT }}
      run: tar zxvf apidocs.tar.gz

    - name: Install Python
      uses: actions/setup-python@v2.3.1
      with: 
        python-version: "${{env.PYTHON_VERSION}}"

    - name: Install Python Dependencies
      run: | 
        curl https://bootstrap.pypa.io/get-pip.py | python && \
        python -m pip install bpystubgen

    - name: Build API Stubs
      working-directory: python_api
      run: |
        python -m bpystubgen --quiet sphinx-in blender-stub && \
        curl https://raw.githubusercontent.com/mysticfall/bpystubgen/main/package/setup.py -o blender-stub/setup.py && \
        curl https://raw.githubusercontent.com/mysticfall/bpystubgen/main/package/README.md -o blender-stub/README.md

    - name: Build Python Package
      working-directory: python_api/blender-stub
      run: |
        sed -i "s/#APP_NAME#/blender/g" setup.py && \
        sed -i "s/#APP_VERSION#/3.0.0/g" setup.py && \
        sed -i "s/#BUILD_NUMBER#/${{ github.run_id }}/g" setup.py && \
        python setup.py sdist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        packages_dir: python_api/blender-stub/dist
        skip_existing: true

