name: publish-for-blender-releases

on:
  release:
    types: [released]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"

jobs:
  build_apis:
    name: Build API Documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        blender_version:
          ["3.64"]

    steps:
    - name: Download Build
      run: |
        curl https://raw.githubusercontent.com/brgr/bpystubgen/main/package/download_blender.sh \
          -o download_blender.sh && \
        bash download_blender.sh "${{matrix.blender_version}}" releases

    - name: Install Tools
      run: | 
        sudo apt update && \
        sudo apt install -y libtbb2 libxi6 libxxf86vm1 libxfixes3 libgl1 \
          libavformat58 libavdevice58 libboost-locale1.74.0

    - name: Install Python
      uses: actions/setup-python@v2.3.1
      with: 
        python-version: "${{env.PYTHON_VERSION}}"

    - name: Install Python Dependencies
      run: | 
        curl https://bootstrap.pypa.io/get-pip.py | python && \
        python -m pip install sphinx yapf tqdm numpy

    - name: Setup Python Path
      run: |
        sudo sh -c "echo '$pythonLocation/lib' >> /etc/ld.so.conf.d/python.conf" && \
        sudo ldconfig

    # - name: Patch Blender Source
    #   if: ${{ !startsWith(matrix.blender_version, '2.8') }}
    #   working-directory: releases/v${{matrix.blender_version}}/src
    #   run: |
    #     sed -i -e "/Hair/s/^/#/" doc/python_api/sphinx_doc_gen.py && \
    #     sed -i -e "/PointCloud/s/^/#/" doc/python_api/sphinx_doc_gen.py

    - name: Prepare API Documentation
      working-directory: releases/v${{matrix.blender_version}}/bin
      run: |
        ./blender --background -noaudio --factory-startup \
                --python ../src/doc/python_api/sphinx_doc_gen.py -- --output ../api

    - name: Clean Up Directories
      if: ${{ !env.ACT }}
      run: |
        rm -Rf releases/v${{matrix.blender_version}}/bin && \
        rm -Rf releases/v${{matrix.blender_version}}/src

    - name: Archive Documents
      if: ${{ !env.ACT }}
      run: tar zcvf apidocs-v${{matrix.blender_version}}.tar.gz releases

    - name: Upload Documents
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: apidocs-v${{matrix.blender_version}}
        path: apidocs-v${{matrix.blender_version}}.tar.gz
        retention-days: 3
